# Generated by Django 4.2.1 on 2023-06-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_alter_cart_pid_alter_cart_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uid',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
